
import type { Product } from './types';

// A lista estática de categorias foi removida para evitar duplicatas,
// já que as categorias agora são carregadas dinamicamente do Firestore.

export const products: Product[] = [
  // Cigarros Sousa Cruz
  { id: 'prod-1', name: 'DUNHILL', description: 'Maço de cigarros Dunhill.', price: 137.80, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-2', name: 'DUNHILL DOUBLE', description: 'Maço de cigarros Dunhill Double.', price: 136.80, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-3', name: 'DUNHILL RED', description: 'Maço de cigarros Dunhill Red.', price: 110.60, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-4', name: 'KENT AZUL', description: 'Maço de cigarros Kent Azul.', price: 112.90, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-5', name: 'KENT PRATA', description: 'Maço de cigarros Kent Prata.', price: 112.90, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-6', name: 'LUCKY STRIKE DOBLE ICE', description: 'Maço de cigarros Lucky Strike Doble Ice.', price: 121.20, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-7', name: 'LUCKY STRIKE VERMELHO', description: 'Maço de cigarros Lucky Strike Vermelho.', price: 73.80, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-8', name: 'MARLBORO RED BOX', description: 'Maço de cigarros Marlboro Red Box.', price: 85.90, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-9', name: 'MARLBORO RED MAÇO', description: 'Maço de cigarros Marlboro Red.', price: 75.90, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-10', name: 'ROTHMANS AZUL', description: 'Maço de cigarros Rothmans Azul.', price: 89.30, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-11', name: 'ROTHMANS PRATA', description: 'Maço de cigarros Rothmans Prata.', price: 89.30, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-12', name: 'ROTHMANS VERMELHO', description: 'Maço de cigarros Rothmans Vermelho.', price: 89.30, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-13', name: 'ROTHMANS GLOBAL AZUL', description: 'Maço de cigarros Rothmans Global Azul.', price: 72.80, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-14', name: 'ROTHMANS GLOBAL VERMELHO', description: 'Maço de cigarros Rothmans Global Vermelho.', price: 72.80, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-15', name: 'ROTHMANS MELANCIA', description: 'Maço de cigarros Rothmans Melancia.', price: 108.30, category: 'CIGARROS SOUSA CRUZ' },
  { id: 'prod-16', name: 'ROTHMANS INTERNACIONAL', description: 'Maço de cigarros Rothmans Internacional.', price: 104.25, category: 'CIGARROS SOUSA CRUZ' },

  // Cigarros Nacional
  { id: 'prod-17', name: 'G BRANCO', description: 'Maço de cigarros G Branco.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-18', name: 'G VERMELHO', description: 'Maço de cigarros G Vermelho.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-19', name: 'PANDORA BRANCO', description: 'Maço de cigarros Pandora Branco.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-20', name: 'PANDORA VERMELHO', description: 'Maço de cigarros Pandora Vermelho.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-21', name: 'NISE VERMELHO', description: 'Maço de cigarros Nise Vermelho.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-22', name: 'NISE BRANCO', description: 'Maço de cigarros Nise Branco.', price: 28.90, category: 'CIGARROS NACIONAL' },
  { id: 'prod-23', name: 'K-LINT SILVER', description: 'Maço de cigarros K-Lint Silver.', price: 0, category: 'CIGARROS NACIONAL' },
  { id: 'prod-24', name: 'GUDANG GARAM (1 CART)', description: 'Cartão de cigarros Gudang Garam.', price: 0, category: 'CIGARROS NACIONAL' },

  // Fumos
  { id: 'prod-25', name: 'FUMO MELIÁ', description: 'Pacote de fumo Meliá.', price: 63.90, category: 'FUMOS' },
  { id: 'prod-26', name: 'FUMO TREVO', description: 'Pacote de fumo Trevo.', price: 81.90, category: 'FUMOS' },

  // Seda
  { id: 'prod-27', name: 'SEDA ZOMO CHOCOLATE', description: 'Seda Zomo sabor Chocolate.', price: 29.90, category: 'SEDA' },
  { id: 'prod-28', name: 'SEDA ZOMO PINK', description: 'Seda Zomo Pink.', price: 27.90, category: 'SEDA' },
  { id: 'prod-29', name: 'SEDA ORGÂNICA', description: 'Seda Orgânica.', price: 25.90, category: 'SEDA' },
  { id: 'prod-30', name: 'SEDA BEM BOLADO', description: 'Seda Bem Bolado.', price: 89.90, category: 'SEDA' },
  { id: 'prod-31', name: 'PAPEL PARA CIGARRO TREVO CAIXA', description: 'Caixa de papel para cigarro Trevo.', price: 44.70, category: 'SEDA' },

  // Isqueiros
  { id: 'prod-32', name: 'BIC', description: 'Isqueiro BIC.', price: 46.50, category: 'ISQUEIROS' },
  { id: 'prod-33', name: 'CRICKET', description: 'Isqueiro Cricket.', price: 26.90, category: 'ISQUEIROS' },
  { id: 'prod-34', name: 'GTI', description: 'Isqueiro GTI.', price: 20.70, category: 'ISQUEIROS' },

  // LONG NECKS
  { id: 'prod-35', name: 'BEATS SENSE', description: 'Long neck Beats Sense.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-36', name: 'BEATS RED MIX 12UNI', description: 'Pack com 12 unidades de Beats Red Mix.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-37', name: 'BEATS GT', description: 'Long neck Beats GT.', price: 135.90, category: 'LONG NECKS' },
  { id: 'prod-38', name: 'BEATS TROPICAL', description: 'Long neck Beats Tropical.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-39', name: 'CABARÉ ICE LIMÃO', description: 'Cabaré Ice sabor Limão.', price: 73.90, category: 'LONG NECKS' },
  { id: 'prod-40', name: 'CABARÉ FRUT VERMELHA', description: 'Cabaré Ice sabor Frutas Vermelhas.', price: 73.90, category: 'LONG NECKS' },
  { id: 'prod-41', name: 'SMIRNOFF ICE', description: 'Long neck Smirnoff Ice.', price: 136.90, category: 'LONG NECKS' },
  { id: 'prod-42', name: 'SMIRNOFF ICE SABORES', description: 'Long neck Smirnoff Ice com sabores variados.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-43', name: 'SPATEN', description: 'Long neck Spaten.', price: 120.90, category: 'LONG NECKS' },
  { id: 'prod-44', name: 'BUDWEISER', description: 'Long neck Budweiser.', price: 122.90, category: 'LONG NECKS' },
  { id: 'prod-45', name: 'STELLA ARTOIS', description: 'Long neck Stella Artois.', price: 130.90, category: 'LONG NECKS' },
  { id: 'prod-46', name: 'CORONA EXTRA', description: 'Long neck Corona Extra.', price: 149.90, category: 'LONG NECKS' },
  { id: 'prod-47', name: 'HEINEKEN', description: 'Long neck Heineken.', price: 137.90, category: 'LONG NECKS' },
  { id: 'prod-48', name: 'STELLA GOLD', description: 'Long neck Stella Gold.', price: 138.90, category: 'LONG NECKS' },
  { id: 'prod-49', name: 'BRAHMA', description: 'Long neck Brahma.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-50', name: 'MICHELOB ULTRA', description: 'Long neck Michelob Ultra.', price: 131.50, category: 'LONG NECKS' },
  { id: 'prod-51', name: 'CORONA EXTRA ZERO', description: 'Long neck Corona Extra Zero Álcool.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-52', name: 'HEINEKEN ZERO', description: 'Long neck Heineken Zero Álcool.', price: 0, category: 'LONG NECKS' },
  { id: 'prod-53', name: 'BUDWEISER ZERO', description: 'Long neck Budweiser Zero Álcool.', price: 112.90, category: 'LONG NECKS' },
  { id: 'prod-54', name: 'BRAHMA ZERO', description: 'Long neck Brahma Zero Álcool.', price: 106.90, category: 'LONG NECKS' },

  // CERVEJAS LATAS
  { id: 'prod-55', name: 'BEATS GREEN MIX (8x269ml)', description: 'Pack com 8 latas de Beats Green Mix 269ml.', price: 37.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-56', name: 'BEATS GT (8x269ml)', description: 'Pack com 8 latas de Beats GT 269ml.', price: 37.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-57', name: 'BEATS TROPICAL (8x269ml)', description: 'Pack com 8 latas de Beats Tropical 269ml.', price: 37.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-58', name: 'BEATS RED MIX', description: 'Lata de Beats Red Mix.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-59', name: 'BEATS CAIPIRINHA', description: 'Lata de Beats Caipirinha.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-60', name: 'BEATS SENSE (Lata)', description: 'Lata de Beats Sense.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-61', name: 'SMIRNOFF ICE SABORES (6x269ml)', description: 'Pack com 6 latas de Smirnoff Ice sabores 269ml.', price: 28.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-62', name: 'SKOL PURO MALTE', description: 'Lata de Skol Puro Malte.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-63', name: 'SKOL (12 und)', description: 'Pack com 12 latas de Skol.', price: 36.40, category: 'CERVEJAS LATAS' },
  { id: 'prod-64', name: 'SKOL (18 und)', description: 'Pack com 18 latas de Skol.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-65', name: 'BRAHMA DUPLO MALTE', description: 'Lata de Brahma Duplo Malte.', price: 41.70, category: 'CERVEJAS LATAS' },
  { id: 'prod-66', name: 'BRAHMA CHOPP', description: 'Lata de Brahma Chopp.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-67', name: 'BUDWEISER (Lata)', description: 'Lata de Budweiser.', price: 42.50, category: 'CERVEJAS LATAS' },
  { id: 'prod-68', name: 'SPATEN (Lata)', description: 'Lata de Spaten.', price: 44.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-69', name: 'STELLA', description: 'Lata de Stella Artois.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-70', name: 'STELLA GOLD (Lata)', description: 'Lata de Stella Gold.', price: 39.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-71', name: 'HEINEKEN (Lata)', description: 'Lata de Heineken.', price: 54.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-72', name: 'CORONA EXTRA (Lata)', description: 'Lata de Corona Extra.', price: 39.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-73', name: 'AMSTEL', description: 'Lata de Amstel.', price: 35.70, category: 'CERVEJAS LATAS' },
  { id: 'prod-74', name: 'BOHEMIA', description: 'Lata de Bohemia.', price: 33.40, category: 'CERVEJAS LATAS' },
  { id: 'prod-75', name: 'PETRA', description: 'Lata de Petra.', price: 0, category: 'CERVEJAS LATAS' },
  { id: 'prod-76', name: 'DEVASSA', description: 'Lata de Devassa.', price: 32.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-77', name: 'ITAIPAVA', description: 'Lata de Itaipava.', price: 29.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-78', name: 'CRISTAL', description: 'Lata de Cristal.', price: 26.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-79', name: 'SCHIN', description: 'Lata de Schin.', price: 28.90, category: 'CERVEJAS LATAS' },
  { id: 'prod-80', name: 'LOKAL', description: 'Lata de Lokal.', price: 25.80, category: 'CERVEJAS LATAS' },

  // CACHAÇAS 1L
  { id: 'prod-81', name: 'YPIOCA PRATA (1L)', description: 'Garrafa de Cachaça Ypioca Prata 1L.', price: 132.50, category: 'CACHAÇAS 1L' },
  { id: 'prod-82', name: 'YPIOCA OURO (1L)', description: 'Garrafa de Cachaça Ypioca Ouro 1L.', price: 189.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-83', name: 'YPIOCA 150 ANOS', description: 'Garrafa de Cachaça Ypioca 150 Anos 1L.', price: 50.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-84', name: 'YPIOCA 160 ANOS', description: 'Garrafa de Cachaça Ypioca 160 Anos 1L.', price: 73.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-85', name: 'YPIOCA 5 CHAVES', description: 'Garrafa de Cachaça Ypioca 5 Chaves 1L.', price: 79.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-86', name: 'YPIOCA EMPALHADA OURO', description: 'Garrafa de Cachaça Ypioca Empalhada Ouro 1L.', price: 419.80, category: 'CACHAÇAS 1L' },
  { id: 'prod-87', name: 'PINGO DE OURO OURO', description: 'Garrafa de Cachaça Pingo de Ouro Ouro 1L.', price: 119.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-88', name: 'PINGO DE OURO PRATA', description: 'Garrafa de Cachaça Pingo de Ouro Prata 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-89', name: 'DOURADINHA OURO (1L)', description: 'Garrafa de Cachaça Douradinha Ouro 1L.', price: 78.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-90', name: 'DOURADINHA PRATA (1L)', description: 'Garrafa de Cachaça Douradinha Prata 1L.', price: 73.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-91', name: 'YPIOCA GUARANÁ', description: 'Garrafa de Ypioca Guaraná 1L.', price: 219.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-92', name: 'YPIOCA LIMA LIMÃO', description: 'Garrafa de Ypioca Lima Limão 1L.', price: 232.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-93', name: 'CABARÉ OURO', description: 'Garrafa de Cachaça Cabaré Ouro 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-94', name: 'CABARÉ AMBURANA', description: 'Garrafa de Cachaça Cabaré Amburana 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-95', name: 'CABARÉ PRATA', description: 'Garrafa de Cachaça Cabaré Prata 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-96', name: 'SAPUPARA OURO (1L)', description: 'Garrafa de Cachaça Sapupara Ouro 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-97', name: 'SAPUPARA PRATA (1L)', description: 'Garrafa de Cachaça Sapupara Prata 1L.', price: 0, category: 'CACHAÇAS 1L' },
  { id: 'prod-98', name: 'YPIOCA MESTRE OURO', description: 'Garrafa de Cachaça Ypioca Mestre Ouro 1L.', price: 297.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-99', name: 'YPIOCA MESTRE PRATA', description: 'Garrafa de Cachaça Ypioca Mestre Prata 1L.', price: 214.95, category: 'CACHAÇAS 1L' },
  { id: 'prod-100', name: 'CACHAÇA 51 OURO', description: 'Garrafa de Cachaça 51 Ouro 1L.', price: 145.90, category: 'CACHAÇAS 1L' },
  { id: 'prod-101', name: 'CACHAÇA 51 PRATA', description: 'Garrafa de Cachaça 51 Prata 1L.', price: 126.90, category: 'CACHAÇAS 1L' },

  // CACHAÇAS MEIOTAS
  { id: 'prod-102', name: 'SAPUPARA OURO', description: 'Meiota de Cachaça Sapupara Ouro.', price: 112.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-103', name: 'SAPUPARA PRATA', description: 'Meiota de Cachaça Sapupara Prata.', price: 92.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-104', name: 'YPIOCA PRATA', description: 'Meiota de Cachaça Ypioca Prata.', price: 0, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-105', name: 'YPIOCA OURO', description: 'Meiota de Cachaça Ypioca Ouro.', price: 117.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-106', name: 'DOURADINHA OURO', description: 'Meiota de Cachaça Douradinha Ouro.', price: 39.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-107', name: 'DOURADINHA PRATA', description: 'Meiota de Cachaça Douradinha Prata.', price: 39.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-108', name: 'D’OURO PRATA', description: 'Meiota de Cachaça D’Ouro Prata.', price: 31.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-109', name: 'D’OURO OURO', description: 'Meiota de Cachaça D’Ouro Ouro.', price: 31.40, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-110', name: 'CARANGUEJO', description: 'Meiota de Cachaça Caranguejo.', price: 0, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-111', name: 'VALE REAL PRATA', description: 'Meiota de Cachaça Vale Real Prata.', price: 25.90, category: 'CACHAÇAS MEIOTAS' },
  { id: 'prod-112', name: 'VALE REAL OURO', description: 'Meiota de Cachaça Vale Real Ouro.', price: 0, category: 'CACHAÇAS MEIOTAS' },

  // VODKAS
  { id: 'prod-113', name: 'SMIRNOFF', description: 'Garrafa de Vodka Smirnoff.', price: 34.90, category: 'VODKAS' },
  { id: 'prod-114', name: 'SLOVA TRADICIONAL', description: 'Garrafa de Vodka Slova Tradicional.', price: 123.90, category: 'VODKAS' },
  { id: 'prod-115', name: 'SLOVA SABORES', description: 'Garrafa de Vodka Slova Sabores.', price: 123.90, category: 'VODKAS' },
  { id: 'prod-116', name: 'ORLOFF', description: 'Garrafa de Vodka Orloff.', price: 24.90, category: 'VODKAS' },
  { id: 'prod-117', name: 'ABSOLUT', description: 'Garrafa de Vodka Absolut.', price: 66.90, category: 'VODKAS' },
  { id: 'prod-118', name: 'SKYY', description: 'Garrafa de Vodka Skyy.', price: 33.90, category: 'VODKAS' },
  { id: 'prod-119', name: 'CIROC', description: 'Garrafa de Vodka Ciroc.', price: 133.90, category: 'VODKAS' },

  // GIN
  { id: 'prod-120', name: 'TANQUERAY', description: 'Garrafa de Gin Tanqueray.', price: 90.90, category: 'GIN' },
  { id: 'prod-121', name: 'BEEFEATER', description: 'Garrafa de Gin Beefeater.', price: 73.90, category: 'GIN' },
  { id: 'prod-122', name: 'BEEFEATER PINK', description: 'Garrafa de Gin Beefeater Pink.', price: 81.90, category: 'GIN' },
  { id: 'prod-123', name: 'BOMBAY', description: 'Garrafa de Gin Bombay.', price: 77.90, category: 'GIN' },
  { id: 'prod-124', name: 'ROCK’S', description: 'Garrafa de Gin Rock’s.', price: 24.90, category: 'GIN' },
  { id: 'prod-125', name: 'INTENCION', description: 'Garrafa de Gin Intencion.', price: 0, category: 'GIN' },
  { id: 'prod-126', name: 'GIN BULLDOG', description: 'Garrafa de Gin Bulldog.', price: 77.95, category: 'GIN' },
  { id: 'prod-127', name: 'GIN TUDO', description: 'Garrafa de Gin Tudo.', price: 22.90, category: 'GIN' },
  { id: 'prod-128', name: 'GIN GORDONS', description: 'Garrafa de Gin Gordons.', price: 57.90, category: 'GIN' },

  // WHISKYS
  { id: 'prod-129', name: 'BLUE LABEL', description: 'Garrafa de Whisky Blue Label.', price: 0, category: 'WHISKYS' },
  { id: 'prod-130', name: 'ROYAL SALUTE', description: 'Garrafa de Whisky Royal Salute.', price: 778.90, category: 'WHISKYS' },
  { id: 'prod-131', name: 'DOUBLE BLACK', description: 'Garrafa de Whisky Double Black.', price: 0, category: 'WHISKYS' },
  { id: 'prod-132', name: 'BUCHANANS', description: 'Garrafa de Whisky Buchanans.', price: 150.90, category: 'WHISKYS' },
  { id: 'prod-133', name: 'GOLD LABEL ED. LIMITADA', description: 'Garrafa de Whisky Gold Label Edição Limitada.', price: 207.90, category: 'WHISKYS' },
  { id: 'prod-134', name: 'GOLD LABEL TRAD (c/ caixa)', description: 'Garrafa de Whisky Gold Label Tradicional com caixa.', price: 225.90, category: 'WHISKYS' },
  { id: 'prod-135', name: 'GREEN LABEL', description: 'Garrafa de Whisky Green Label.', price: 0, category: 'WHISKYS' },
  { id: 'prod-136', name: 'JACK DANIEL’S TRADICIONAL', description: 'Garrafa de Whisky Jack Daniel’s Tradicional.', price: 122.90, category: 'WHISKYS' },
  { id: 'prod-137', name: 'JACK DANIEL’S MAÇÃ VERDE', description: 'Garrafa de Whisky Jack Daniel’s Maçã Verde.', price: 123.90, category: 'WHISKYS' },
  { id: 'prod-138', name: 'JACK DANIEL’S HONEY', description: 'Garrafa de Whisky Jack Daniel’s Honey.', price: 0, category: 'WHISKYS' },
  { id: 'prod-139', name: 'JACK DANIEL’S FIRE', description: 'Garrafa de Whisky Jack Daniel’s Fire.', price: 122.90, category: 'WHISKYS' },
  { id: 'prod-140', name: 'BLACK LABEL', description: 'Garrafa de Whisky Black Label.', price: 0, category: 'WHISKYS' },
  { id: 'prod-141', name: 'OLD PAR', description: 'Garrafa de Whisky Old Par.', price: 120.90, category: 'WHISKYS' },
  { id: 'prod-142', name: 'CHIVAS', description: 'Garrafa de Whisky Chivas.', price: 103.90, category: 'WHISKYS' },
  { id: 'prod-143', name: 'BALLANTINES', description: 'Garrafa de Whisky Ballantines.', price: 66.90, category: 'WHISKYS' },
  { id: 'prod-144', name: 'CAVALO BRANCO', description: 'Garrafa de Whisky Cavalo Branco.', price: 58.90, category: 'WHISKYS' },
  { id: 'prod-145', name: 'RED LABEL', description: 'Garrafa de Whisky Red Label.', price: 76.90, category: 'WHISKYS' },
  { id: 'prod-146', name: 'BLACK WHITE', description: 'Garrafa de Whisky Black & White.', price: 55.90, category: 'WHISKYS' },
  { id: 'prod-147', name: 'OLD EIGHT', description: 'Garrafa de Whisky Old Eight.', price: 0, category: 'WHISKYS' },

  // DESTILADOS
  { id: 'prod-148', name: 'APEROL', description: 'Garrafa de Aperol.', price: 37.90, category: 'DESTILADOS' },
  { id: 'prod-149', name: 'CAMPARI', description: 'Garrafa de Campari.', price: 49.50, category: 'DESTILADOS' },
  { id: 'prod-150', name: 'CONHAQUE DREHER', description: 'Garrafa de Conhaque Dreher.', price: 199.90, category: 'DESTILADOS' },
  { id: 'prod-151', name: 'RUM MONTILLA', description: 'Garrafa de Rum Montilla.', price: 0, category: 'DESTILADOS' },
  { id: 'prod-152', name: 'CONHAQUE SÃO JOÃO DA BARRA', description: 'Garrafa de Conhaque São João da Barra.', price: 0, category: 'DESTILADOS' },
  { id: 'prod-153', name: 'TEQUILA JOSÉ CUERVO', description: 'Garrafa de Tequila José Cuervo.', price: 98.90, category: 'DESTILADOS' },
  { id: 'prod-154', name: 'TEQUILA TEQPAR', description: 'Garrafa de Tequila Teqpar.', price: 21.90, category: 'DESTILADOS' },
  { id: 'prod-155', name: 'MARTINI ROSSO', description: 'Garrafa de Martini Rosso.', price: 35.40, category: 'DESTILADOS' },
  { id: 'prod-159', name: 'LICOR 43', description: 'Garrafa de Licor 43.', price: 0, category: 'DESTILADOS' },
  { id: 'prod-160', name: 'XAROPE MONIN', description: 'Garrafa de Xarope Monin.', price: 55.90, category: 'DESTILADOS' },
  { id: 'prod-161', name: 'EL JIMADOR', description: 'Garrafa de Tequila El Jimador.', price: 0, category: 'DESTILADOS' },

  // LICORES
  { id: 'prod-156', name: 'BALLENA MORANGO', description: 'Garrafa de Licor Ballena Morango.', price: 118.90, category: 'LICORES' },
  { id: 'prod-157', name: 'BALLENA CHOCOLATE', description: 'Garrafa de Licor Ballena Chocolate.', price: 119.90, category: 'LICORES' },
  { id: 'prod-158', name: 'BALLENA COCO', description: 'Garrafa de Licor Ballena Coco.', price: 0, category: 'LICORES' },

  // VINHOS
  { id: 'prod-162', name: 'VINHO PÉRGULA', description: 'Garrafa de Vinho Pérgula.', price: 271.90, category: 'VINHOS' },
  { id: 'prod-163', name: 'QUINTA DO MORGADO', description: 'Garrafa de Vinho Quinta do Morgado.', price: 141.90, category: 'VINHOS' },
  { id: 'prod-164', name: 'O GAÚCHO', description: 'Garrafa de Vinho O Gaúcho.', price: 0, category: 'VINHOS' },
  { id: 'prod-165', name: 'SÃO BRAZ', description: 'Garrafa de Vinho São Braz.', price: 59.90, category: 'VINHOS' },
  { id: 'prod-166', name: 'SÃO BRAZ PINK', description: 'Garrafa de Vinho São Braz Pink.', price: 0, category: 'VINHOS' },
  { id: 'prod-167', name: 'VALE REAL', description: 'Garrafa de Vinho Vale Real.', price: 0, category: 'VINHOS' },
  { id: 'prod-168', name: 'CAMPESTRE', description: 'Garrafa de Vinho Campestre.', price: 41.90, category: 'VINHOS' },
  { id: 'prod-169', name: 'CASAL GARCIA', description: 'Garrafa de Vinho Casal Garcia.', price: 52.90, category: 'VINHOS' },
  { id: 'prod-170', name: 'CASAL GARCIA SWEET', description: 'Garrafa de Vinho Casal Garcia Sweet.', price: 54.60, category: 'VINHOS' },
  { id: 'prod-171', name: 'VINHO CHILENO STA HELENA', description: 'Garrafa de Vinho Chileno Santa Helena.', price: 28.90, category: 'VINHOS' },

  // ENERGÉTICOS
  { id: 'prod-172', name: 'RED BULL TRADICIONAL', description: 'Lata de Red Bull Tradicional.', price: 0, category: 'ENERGÉTICOS' },
  { id: 'prod-173', name: 'RED BULL MELANCIA', description: 'Lata de Red Bull Melancia.', price: 171.90, category: 'ENERGÉTICOS' },
  { id: 'prod-174', name: 'RED BULL TROPICAL', description: 'Lata de Red Bull Tropical.', price: 0, category: 'ENERGÉTICOS' },
  { id: 'prod-175', name: 'RED BULL ZERO', description: 'Lata de Red Bull Zero.', price: 159.90, category: 'ENERGÉTICOS' },
  { id: 'prod-176', name: 'MONSTER TRADICIONAL', description: 'Lata de Monster Tradicional.', price: 46.90, category: 'ENERGÉTICOS' },
  { id: 'prod-177', name: 'MONSTER ZERO', description: 'Lata de Monster Zero.', price: 46.90, category: 'ENERGÉTICOS' },
  { id: 'prod-178', name: 'MONSTER SABORES', description: 'Lata de Monster Sabores.', price: 46.90, category: 'ENERGÉTICOS' },
  { id: 'prod-179', name: 'NIGHT POWER LATA', description: 'Lata de Night Power.', price: 0, category: 'ENERGÉTICOS' },
  { id: 'prod-180', name: 'NIGHT POWER TRADICIONAL 2L', description: 'Garrafa de Night Power Tradicional 2L.', price: 0, category: 'ENERGÉTICOS' },
  { id: 'prod-181', name: 'NIGHT POWER SABORES 2L', description: 'Garrafa de Night Power Sabores 2L.', price: 0, category: 'ENERGÉTICOS' },
  { id: 'prod-182', name: 'BALY 2L', description: 'Garrafa de Baly 2L.', price: 66.90, category: 'ENERGÉTICOS' },
];

